### ISSUE TITLE
ModuleNotFoundError: No module named 'protonets.utils'

### ISSUE THREAD

**Issue by Chibuikem709** [jakesnell/prototypical-networks#14]
Hello!

I am trying to replicate this experiment,  but when I run the following command: 
`python scripts/train/few_shot/run_train.py --data.cuda --log.exp_dir results`

I get the following error: 

`Traceback (most recent call last):
  File "scripts/train/few_shot/run_train.py", line 3, in <module>
    from train import main
  File "/gpfs/data/lcrawfo1/cnwizu/PythonSandbox/prototypical-networks-master/scripts/train/few_shot/train.py", line 16, in <module>
    import protonets.utils.data as data_utils
ModuleNotFoundError: No module named 'protonets.utils'`

I followed the readme exactly. What is the solution?

Thanks in advance!

**Comment by SherryWang00** [comment]
I think you may need to edit the setup.py file: change the command line "packages=['protonets']" into "packages=['protonets', 'protonets.utils', 'protonets.data', 'protonets.models']"

**Comment by SherryWang00** [comment]
> Hello!
> 
> I am trying to replicate this experiment, but when I run the following command:
> `python scripts/train/few_shot/run_train.py --data.cuda --log.exp_dir results`
> 
> I get the following error:
> 
> `Traceback (most recent call last): File "scripts/train/few_shot/run_train.py", line 3, in <module> from train import main File "/gpfs/data/lcrawfo1/cnwizu/PythonSandbox/prototypical-networks-master/scripts/train/few_shot/train.py", line 16, in <module> import protonets.utils.data as data_utils ModuleNotFoundError: No module named 'protonets.utils'`
> 
> I followed the readme exactly. What is the solution?
> 
> Thanks in advance!

I think you may need to edit the setup.py file: change the command line "packages=['protonets']" into "packages=['protonets', 'protonets.utils', 'protonets.data', 'protonets.models']"

**Comment by Ha0Tang** [comment]
I am meeting the same problem, have you solved it?

**Comment by SherryWang00** [comment]
> I am meeting the same problem, have you solved it?

Yeah,,, I made it work by editting the setup.py file: change the command line "packages=['protonets']" into "packages=['protonets', 'protonets.utils', 'protonets.data', 'protonets.models']".
